routes/web.php
Route::post('/send/{id}', 'PrivateChatController@store');
Route::post('/geturl', 'PrivateChatController@geturl');
Route::post('/timeformate', 'PrivateChatController@timeformate');
Route::post('/setuserlocalutc', 'PrivateChatController@setuserlocalutc');
Route::get('/getlogedinusertime', 'PrivateChatController@getlogedinusertime')->name('getlogedinusertime');

Route::post('/getOldMessage', 'ChatController@getOldMessage');
Route::post('/chatSpam/{id}', 'ChatController@spam');
Route::post('/chatReport/{id}', 'ChatController@report');
Route::get('/chatsearch', 'searchController@search')->name('chatsearch');
Route::get('/defaullevelsearch', 'searchController@defaullevelsearch')->name('defaullevelsearch');
Route::get('/levelsearch', 'searchController@levelsearch')->name('levelsearch');
Route::get('/unreadsearch', 'searchController@unreadsearch')->name('unreadsearch');
Route::get('/indeviduallevelsearch', 'searchController@indeviduallevelsearch')->name('indeviduallevelsearch');

Route::post('/setonline', 'ChatController@setonline');
Route::post('/setoffline', 'ChatController@setoffline');
Route::post('/getallOnlineUser', 'ChatController@getallOnlineUser');
Route::post('/readwrite', 'ChatController@readwrite');

Route::get('/levelset', 'LevelController@index')->name('levelset');
Route::get('/getOldLevel', 'LevelController@getOldLevel');
Route::post('/addcustomlevel', 'LevelController@custom');
Route::get('/leveldel/{id}', 'LevelController@delete')->name('leveldel');
Route::get('/starchat/{id}', 'LevelController@starchat')->name('starchat');
Route::get('/delallchat/{id}', 'LevelController@delallchat');
Route::get('/getmessagepopup', 'messagepopController@index')->name('messagepop');
Route::get('/getmessagepopupcross', 'messagepopController@getmessagepopupcross');

Route::get('/gmtime', 'PrivateChatController@test');
Route::get('/testtt', 'searchController@test');
Route::get('/sendemailforunread', 'PrivateChatController@sendemailforunread');
Route::post('/sendmail', 'PrivateChatController@sendmail');

//end of chat..........
Route::post('getAndMoveVerifyDetails', 'PageController@getAndMoveVerifyDetails')->name('getAndMoveVerifyDetails');
Route::get('getMemberDetailsUsingEmail', 'PageController@getMemberDetailsUsingEmail')->name('getMemberDetailsUsingEmail');
//////////////////////// Blog /////////////////////////////

Route::get('/blog', 'PublicBlogContoller@index')->name('blog');

Route::get('/my-blog', 'BlogController@myBlog')->name('my.blog');
Route::get('/add-blog', 'BlogController@addBlog')->name('add.blog');
Route::post('/blog/store', 'BlogController@storeBlog');
Route::get('/public-blog', 'BlogController@publicBlog');
Route::get('/userprofile/{id}/blog', 'BlogController@userProfileBlog')->name('user.profile.blog');
Route::get('/blod-details/{ids}', 'BlogController@blogDetails')->name('blog.article.detail');
Route::post('/add_comment/{post_id}/{user_id}','BlogController@addComment');
Route::get('/delete_post/{post_id}', 'BlogController@deletePost');
Route::get('/delete_comment/{comment_id}', 'BlogController@deleteComment');
Route::get('/visitors-details/{ids}', 'BlogController@visitorDetails');
Route::post('/blog/update/reaction', 'BlogController@updateBlogReaction');
Route::get('/blog/pay-to-read/{amount}/{owner_id}','BlogController@payToRead');

/////////////////////// Sakib changes ///////////////////

Route::resource('/events', 'EventsController');
Route::resource('/eventM', 'EventModalController');
Route::get('/search', 'EventsController@search')->name('search');
Route::get('/going-to-event/{user_id}/{owner_id}/{event_id}/{event_modal_id}','EventsController@goingToEvent');
Route::get('/not-going-to-event/{user_id}/{owner_id}/{event_id}/{event_modal_id}','EventsController@notGoingToEvent');
Route::get('/going-status/{status}/{user_id}/{event_id}/{amount}','EventsController@eventStatus');
//get records
Route::post('/get_records', 'DisputeController@getRecords')->name('getRecords');
Route::post('/event/invite/{event_id}','EventsController@eventInvite');
Route::get('/event/draft/{user_id}','EventsController@draftEvents');
Route::get('/draft/add-plan/{event_id}','EventsController@draftAddPlan');
Route::get('/event/plan&price/{event_id}','EventsController@eventPlanPrice');
Route::get('/event/passed','EventsController@passedEvents');
Route::get('/event/club-events','EventsController@clubEvents');
Route::get('/event/club-member-events','EventsController@clubMemberEvents');
//dispute work
Route::get('/dispute', 'DisputeController@create')->name('dispute');
Route::post('/add_dispute', 'DisputeController@addDispute')->name('adddispute');
Route::post('/get_all_dis_rec', 'DisputeController@getallDispute')->name('getallDispute');

Route::get('events/profile/{user_id}', 'EventsController@profileEvents')->name('events.profile.index');
Route::get('save-event/{event_id}', 'EventsController@saveEvent')->name('events.save');

Route::post('/get_note_of_record', 'DisputeController@getNoteOfRecord')->name('getNoteOfRecord');

//Event start date ane last date insert
Route::post('/events/datetimeInsert', 'EventModalController@insertStartDateTime');
//insert event model data 
Route::post('/events/eventInsert', 'EventModalController@eventInsert');
//update going status
Route::post('/events/goingStatusUpdate', 'EventModalController@goingEventStatus');
//event model edit
Route::post('/events/eventModelEdit', 'EventModalController@eventModelEdit');
//event model saved post
Route::post('/events/eventModelsaved', 'HomeController@eventModelSaved');
//event model Edit date time list
Route::post('/events/eventEditDateTime', 'EventModalController@eventEditDateTime');
//event model Edit add date time
Route::post('/events/editEventDateTime', 'EventModalController@editEventDateTime');
//event delete
Route::post('/events/eventDelete', 'EventModalController@eventDelete');
//event fee pay function
Route::get('/events/joinToPay/{amount}/{owner_id}/{id}/{modelId}/{needApproval}','HomeController@payToJoin');
//free join event 
Route::get('/events/freeJoinToPay/{owner_id}/{id}/{modelId}/{needApproval}','HomeController@freeJoinToPay');
//going event participent list
Route::post('/events/goingParticipentList','EventModalController@goingParticipentList');
//waiting event participent list
Route::post('/events/waitingParticipentList','EventModalController@waitingParticipentList');
//update event request need to approval
Route::post('/events/updateEventRequest','EventModalController@updateEventRequest');
//reject event request need to approval
Route::post('/events/rejectEventRequest','EventModalController@rejectEventRequest');
//edit selected event date time
Route::post('/events/selectChangeDateTime','EventModalController@selectChangeDateTime');
//update event date time
Route::post('/events/updateSelectedDateTime','EventModalController@updateSelectedDateTime');
//delete event date time
Route::post('/events/deleteEventDateTime','EventModalController@deleteEventDateTime');
//event model unsaved post
Route::post('/events/eventModelUnsaved', 'HomeController@eventModelUnsaved');
//edit event edit selected event date time
Route::post('/events/selectEditChangeDateTime','EventModalController@selectChangeDateTime');
//delete event date time
Route::post('/events/deleteListEventDateTime','EventModalController@deleteListEventDateTime');
//cancel join request
Route::get('/events/cancelToJoin/{userId}/{eventId}/{eventModelId}/{amount}','HomeController@cancelToJoin');

 Route::get('/share/{event_id}/{user_id}', 'ShareController@eventShareDesign');

 Route::get('/activeEvent', 'EventsController@activeEvent')->name('activeEvent');
 Route::get('/goingEvent', 'EventsController@goingEvent')->name('goingEvent');
 Route::get('/pastEvent', 'EventsController@pastEvent')->name('pastEvent');
 Route::get('/closeEvent', 'EventsController@closeEvent')->name('closeEvent');

 Route::get('/events/insertReferral/{ownerId}/{event_id}/{eventRef}','HomeController@insertReferral');

//////////////Rafi's Changes/////////////////
Route::group(
    [
        'prefix' => 'bids',
    ],
    function(){
        Route::resource('buyers', 'Bids\BuyerController');
    }
);

// //////////////Rafi's Changes/////////////////
// Route::group(
//     [
//         'prefix' => 'bids',
//     ],
//     function(){
//         Route::resource('buyers', 'Bids\BuyerController');
//     }
// );
// //matul bidf
Route::get('/bids/user-bids','bidController@userBids')->name('bids.user.index');
Route::get('/bids/buyers','bidController@index')->name('bids.buyers.index');
Route::get('/buyer_bid_form','bidController@showform');
Route::post('/save-bid-form','bidController@store');
Route::get('/edit-bid-form/{id}','bidController@edit');
Route::post('/edit-bid-form/{id}','bidController@editstore');



Route::group(['prefix' => 'settings'], function() {
    Route::get('/', 'SettingsController@index')->name('settings');
    Route::post('env', 'SettingsController@updateEnv');
});

Route::get('/bids/buyers/delete/{id}','bidController@delete');


/*Follow user routes*/
Route::post('follow_user', 'FollowController@followUser')->name('follow.user');
Route::post('review_user', 'ReviewController@reviewUser')->name('review.user');
Route::post('total_review','ReviewController@getAverageTotalReview')->name('get.average.total.review');

//Faq Category Route
Route::group([ 'prefix' => 'faq','middleware' => 'auth'], function() {

    Route::get('/category', 'FaqCategoryController@index')->name('faq.category.index');
    Route::post('/category', 'FaqCategoryController@store')->name('faq.category.store');
    Route::get('/category/edit/{faq}', 'FaqCategoryController@edit')->name('faq.category.edit');
    Route::put('/category/edit/{faq}', 'FaqCategoryController@update')->name('faq.category.update');
    Route::delete('/category/destroy/{faq}', 'FaqCategoryController@destroy')->name('faq.category.destroy');

});

//By tuhin
Route::group(['middleware' => 'auth'], function() {

app/Event.php
<?php

namespace App;

use ChristianKuri\LaravelFavorite\Traits\Favoriteable;
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    use Favoriteable;

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function eventModals()
    {
        return $this->hasMany(EventModal::class, 'event_id');
    }


}

resources/views/pages/events/club__member_events.blade.php
@extends('layouts.app')
@section('custom-styles')
<link rel="stylesheet" href="{{ asset('css/tempusdominus-bootstrap-4.css') }}">
{{-- <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/2.3.2/css/bootstrap.min.css"> --}}
<link rel="stylesheet" href="{{asset('css/style.css')}}">
<link href="http://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
@endsection
@section('content')
<section id="section-sidebar-left">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="form-row">
          <div class="form-group col-md-10 m-auto text-center">
            <img id="user_avatar_img" src="{{ asset('/uploads/avatars/' . Auth::user()->avatar) }}"
            style="width:100px; height:100px; border-radius:50%;">
          </div>
          <form id="search-user" action="{{ URL('/search') }}" method="GET" role="search">
            <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
            <div class="form-group col-md-10 m-auto">
              @if (session('status'))
                  <div class="alert alert-success">
                      {{ session('status') }}
                  </div>
              @endif
              <div class="input-group" style="width: 297px;margin-left: -56px;">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-user"></i></div>
                </div>
                <input class="form-control" id="find_email" name="find_email" type="search" placeholder="Search" aria-label="Search" value="{{ old('find_email') }}">
                <div class="input-group-append">
                  <button class="btn btn-secondary search_user" type="submit" id="button-addon2">
                    <i class="fas fa-search"></i>
                  </button>
                </div>
              </div>
            </div>
          </form>
        </div>
        <br>
           
                <div class="row">
                    <div class="col-md-8 ">
                        <div class="example1" style="margin:0 auto;margin-left: -25px !important;"></div>
                    </div>
                </div>
      
        <br>
        <div class="col-md-12" style="border:1px solid gray;padding-bottom:5px;padding-top:20px;padding-left:0px;padding-right:0px;width:295px !important;margin-left:-20px;max-width:295px">
         
              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-bottom: 10px;">
                  <ul class="ul-schedule-list">
                    <li class="" >
                      <a href=""><i class="fas fa-square"></i> &nbsp; All Events</a>
                    </li>
                  </ul>
              </div>
              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-top: 20px;padding-bottom: 20px;">
                  <ul class="ul-schedule-list">
                      <li class="" style="padding-bottom: 10px;">
                        <a href="/event/club-events"><i class="fa fa-circle" style="color: pink;" aria-hidden="true"></i> &nbsp; Club Events</a>
                      </li>
                      <li class="">
                          <a href="/event/club-member-events"><i class="fa fa-circle" style="color: blue;" aria-hidden="true"></i> &nbsp; Club Member Events</a>
                        </li>
                    </ul>
              </div>

              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-top: 20px;padding-bottom: 20px;">
                  <ul class="ul-schedule-list">
                      <li class="" style="padding-bottom: 10px;" >
                        <a href=""><i class="fa fa-circle" style="color: purple;" aria-hidden="true"></i> &nbsp;Events Opened by Me</a>
                      </li>
                      <li class="">
                          <a href=""><i class="fa fa-circle" style="color: yellow;" aria-hidden="true"></i> &nbsp;Waiting for my approval</a>
                        </li>
                    </ul>
              </div>
              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-top: 20px;padding-bottom: 20px;">
                  <ul class="ul-schedule-list">
                      <li class="" style="padding-bottom: 10px;">
                        <a href=""><i class="fa fa-circle" style="color: red;" aria-hidden="true"></i> &nbsp;I am waiting for approval</a>
                      </li>
                      <li class="" >
                          <a href=""><i class="fa fa-circle" style="color: green;" aria-hidden="true"></i> &nbsp; Event Booked By Me</a>
                        </li>
                    </ul>
              </div>
              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-top: 15px;padding-bottom: 15px;">
                  <ul class="ul-schedule-list">
                    <li class="" >
                        <a href="{{ route('events.create') }}">  <i class="fas fa-plus"></i> &nbsp Add new Event</a>
                    </li>
                    <li class="" >
                        <a href="/event/draft/{{Auth::user()->id}}">  <i class="fas fa-save"></i> &nbsp Draft Events</a>
                    </li>
                    <li class="" >
                      <a href="/event/passed">  <i class="fas fa-save"></i> &nbsp Passed Events</a>
                  </li>
                  </ul>
              </div>
              <div class="ul-schedule-list" style="padding-top: 20px;padding-bottom: 20px;">
                  <ul class="ul-schedule-list">
                    <li class="" >
                      <a href=""><i class="fas fa-certificate"></i> &nbsp; My Availability</a>
                    </li>
                  </ul>
              </div>
                
                {{-- <h5 class="mt-4">Schedule</h5> --}}
                {{-- <ul class="ul-schedule-list">
                  <li class="li-schedule-list mylist" >
                    <a href="">Waiting for approval</a>
                  </li>
                  
                  <li class="li-schedule-list">
                    <a href="">Asked my schedule</a>
                  </li>
                  <li class="li-schedule-list">
                    <a href="">Booked schedule</a>
                  </li>
                  <li class="li-schedule-list">
                    <a href="{{ route('events.create') }}">Add a schedule</a>
                  </li>
                  <li class="li-schedule-list">
                    <a href="">Ask a schedule</a>
                  </li>
                </ul>
                {{-- <h5 class="mt-4">Events</h5> --}}
                {{-- <ul class="ul-event-list">
                  <li class="li-event-list">
                    <a href="">Club events</a>
                  </li>
                  <li class="li-event-list">
                    <a href="">Joining events</a>
                  </li>
                  <li class="li-event-list">
                    <a href="">My open events</a>
                  </li>
                  <li class="li-event-list">
                    <a href="">Add New event</a>
                  </li>
                </ul>  --}}
            
            
        </div>
      </div>
      
      <div class="col-md-9">
        <div class="row">
          
          @foreach ($finalEvents as $event)
          <div class="col-sm-4">
            <div class="card">
              <div class="card-img-top">
                <a href="{{ route('events.show', $event->id) }}">
                  <img src="{{ asset('uploads/event/' . $event->event_featured_image) }}" style="width: 100%;">
                </a>
              </div>
              <div class="card-body">
                <div class="row">
                    <div class="col-md-12 p-0 pl-2">

                      
                     <h3>{{ $event->event_title }}</h3>

                    </div>
                </div>  
                <hr id="event_view_border">

                <div class="row">
                  <?php $going_modal = 0; ?>
                  @foreach($comingDates as $date)
                    @if($event->id == $date->event_id)
                    <?php  $going_modal = $date->id; ?>
                      <div class="col-md-5 p-0 pl-2">
                        <div class="h5 text-danger "><strong>{{ date('M', strtotime($date->event_date)) }}</strong></div>
                        <div class="h5 mt-0">{{ date('j', strtotime($date->event_date)) }}</div>
                      </div>
                    @endif
                  @endforeach  
                  <div class="col-md-7 p-0 pl-2">

                  
                  <label class="" for="" style="">Online</label><br>
                  @if(empty($event->interested_in_event))
                  0 interested
                  @else
                  {{ ($event->interested_in_event) }} interested
                  @endif
                  <br>
                  @if(empty($event->going_in_event))
                      0 going
                   @else
                     {{ ($event->going_in_event) }} going
                   @endif
                  </div>
                </div>
                <div class="row">
                  
                  <div class="col-md-4 ">

                    
                  </div>
                </div>
                <div class="row" style="margin-top:10px">
                  <div class="col-md-6">
                    <div class="text-muted">
                        {{ $event->event_city }}
                      
                      </div>
                  </div>
                  <div class="col-md-6">
                      <div class="text-muted">
                      
                          {{ $event->event_country }}
                        </div>
                    </div>
                    
                </div>
                
              </div>
              

              <div class="col-md-12" style="margin-bottom:5px">
                  <hr id="event_view_border">
                  <button class="btn btn-default">
                    <a href="#"><i class="fas fa-share-square fa-1x"></i></a>
                  </button>
                  <button class="btn btn-default">
                    <a href="#"><i class="far fa-star fa-1x"></i></a>
                  </button>

                    <?php $flag=false ?>
                    
                    @foreach ($eventVisitors as $eventVisitor)
              

                      @if($eventVisitor->user_id == Auth::user()->id && $eventVisitor->event_id == $event->id )

                      <?php $flag=true; ?>
                        <a class="btn btn-default" type="button"  name="event_not_going" style="float:right;"
                          href="/not-going-to-event/{{Auth::user()->id}}/{{$event->user_id}}/{{$event->id}}/{{$going_modal}}"> <i class="fa fa-times fa-1x"></i> going 
                      </a>
                        
                      {{-- @else
                      
                        <a class="btn btn-default" type="button"  name="event_not_going" style="float:right;"
                          href="/not-going-to-event/{{Auth::user()->id}}/{{$event->user_id}}/{{$event->id}}"> <i class="fa fa-times fa-1x"></i> going 
                        </a> --}}

                      @endif

                    @endforeach

                    <?php if($flag == false){ ?>
                    
                      <a class="btn btn-default" type="button"  name="event_not_going" style="float:right;"
                    href="/going-to-event/{{Auth::user()->id}}/{{$event->user_id}}/{{$event->id}}/{{$going_modal}}"> <i class="fa fa-check fa-1x"></i> going 
                        </a> 
                      
                    <?php } ?>
                
                </div>
            </div>
          </div>
          @endforeach
      </div>
    </div>
  </div>
  <div class="text-center">
    {{-- {!! $events->links(); !!} --}}
  </div>
</div>
</section>
@endsection

@section('extra-JS')
<script src="{{ asset('js/jquery.supercal.js')}}"></script> 
<script type="text/javascript">
	$('.example1').supercal({
				transition: 'carousel-vertical'
			});
    $(function () {
        $('#datetimepicker13').datetimepicker({
           
        });
    });
</script>
@endsection

resources/views/pages/events/draft.blade.php
@extends('layouts.app')
@section('custom-styles')
<link rel="stylesheet" href="{{ asset('css/tempusdominus-bootstrap-4.css') }}">
{{-- <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/2.3.2/css/bootstrap.min.css"> --}}
<link rel="stylesheet" href="{{asset('css/style.css')}}">
<link href="http://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
@endsection
@section('content')
<section id="section-sidebar-left">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="form-row">
          <div class="form-group col-md-10 m-auto text-center">
            <img id="user_avatar_img" src="{{ asset('/uploads/avatars/' . Auth::user()->avatar) }}"
            style="width:100px; height:100px; border-radius:50%;">
          </div>
          <form id="search-user" action="{{ URL('/search') }}" method="GET" role="search">
            <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
            <div class="form-group col-md-10 m-auto">
              @if (session('status'))
                  <div class="alert alert-success">
                      {{ session('status') }}
                  </div>
              @endif
              <div class="input-group" style="width: 297px;margin-left: -56px;">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-user"></i></div>
                </div>
                <input class="form-control" id="find_email" name="find_email" type="search" placeholder="Search" aria-label="Search" value="{{ old('find_email') }}">
                <div class="input-group-append">
                  <button class="btn btn-secondary search_user" type="submit" id="button-addon2">
                    <i class="fas fa-search"></i>
                  </button>
                </div>
              </div>
            </div>
          </form>
        </div>
        <br>
           
                <div class="row">
                    <div class="col-md-8 ">
                        <div class="example1" style="margin:0 auto;margin-left: -25px !important;"></div>
                    </div>
                </div>
      
        <br>
        <div class="col-md-12" style="border:1px solid gray;padding-bottom:5px;padding-top:20px;padding-left:0px;padding-right:0px;width:295px !important;margin-left:-20px;max-width:295px">
         
              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-bottom: 10px;">
                  <ul class="ul-schedule-list">
                    <li class="" >
                      <a href="/events"><i class="fas fa-square"></i> &nbsp; All Events</a>
                    </li>
                  </ul>
              </div>
              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-top: 20px;padding-bottom: 20px;">
                  <ul class="ul-schedule-list">
                      <li class="" style="padding-bottom: 10px;">
                        <a href=""><i class="fa fa-circle" style="color: pink;" aria-hidden="true"></i> &nbsp; Club Events</a>
                      </li>
                      <li class="">
                          <a href=""><i class="fa fa-circle" style="color: blue;" aria-hidden="true"></i> &nbsp; Club Member Events</a>
                        </li>
                    </ul>
              </div>

              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-top: 20px;padding-bottom: 20px;">
                  <ul class="ul-schedule-list">
                      <li class="" style="padding-bottom: 10px;" >
                        <a href=""><i class="fa fa-circle" style="color: purple;" aria-hidden="true"></i> &nbsp;Events Opened by Me</a>
                      </li>
                      <li class="">
                          <a href=""><i class="fa fa-circle" style="color: yellow;" aria-hidden="true"></i> &nbsp;Waiting for my approval</a>
                        </li>
                    </ul>
              </div>
              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-top: 20px;padding-bottom: 20px;">
                  <ul class="ul-schedule-list">
                      <li class="" style="padding-bottom: 10px;">
                        <a href=""><i class="fa fa-circle" style="color: red;" aria-hidden="true"></i> &nbsp;I am waiting for approval</a>
                      </li>
                      <li class="" >
                          <a href=""><i class="fa fa-circle" style="color: green;" aria-hidden="true"></i> &nbsp; Event Booked By Me</a>
                        </li>
                    </ul>
              </div>
              <div class="ul-schedule-list" style="border-bottom:1px solid gray;padding-top: 15px;padding-bottom: 15px;">
                  <ul class="ul-schedule-list">
                    <li class="" >
                        <a href="{{ route('events.create') }}">  <i class="fas fa-plus"></i> &nbsp Add new Event</a>
                    </li>
                    <li class="" >
                        <a href="{{ route('events.create') }}">  <i class="fas fa-save"></i> &nbsp Draft Events</a>
                    </li>
                  </ul>
              </div>
              <div class="ul-schedule-list" style="padding-top: 20px;padding-bottom: 20px;">
                  <ul class="ul-schedule-list">
                    <li class="" >
                      <a href=""><i class="fas fa-certificate"></i> &nbsp; My Availability</a>
                    </li>
                  </ul>
              </div>
                
            
            
        </div>
      </div>
      
      <div class="col-md-9">
        <div class="row">
          
          @foreach ($draftEevents as $event)
          <div class="col-sm-4">
            <div class="card">
              <div class="card-img-top">
                <a href="/draft/add-plan/{{$event->id}}">
                  <img src="{{ asset('uploads/event/' . $event->event_featured_image) }}" style="width: 100%;">
                </a>
              </div>
              <div class="card-body">
                <div class="row">
                    <div class="col-md-12 p-0 pl-2">

                      
                     <h3>{{ $event->event_title }}</h3>

                    </div>
                </div>  
                <hr id="event_view_border">
                <div class="row" style="margin-top:10px">
                  <div class="col-md-12">
                    <div class="text-muted">
                        City : {{ $event->event_city}}
                      
                      </div>
                  </div>
                </div>
                <div class="row" style="margin-top:10px">

                  <div class="col-md-12">
                      <div class="text-muted">
                      
                         Country :  {{ $event->event_country }}
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-top:10px">

                    <div class="col-md-12">
                        <div class="text-muted">
                           
                          Phone :  {{ $event->event_phone  }}
                          </div>
                      </div>
                </div>
                <hr id="event_view_border">

                
              </div>
             
            </div>
          </div>
          @endforeach
      </div>
    </div>
  </div>
  <div class="text-center">
    {{-- {!! $events->links(); !!} --}}
  </div>
</div>
</section>
@endsection

@section('extra-JS')
<script src="{{ asset('js/jquery.supercal.js')}}"></script> 
<script type="text/javascript">
	$('.example1').supercal({
				transition: 'carousel-vertical'
			});
    $(function () {
        $('#datetimepicker13').datetimepicker({
           
        });
    });
</script>
@endsection